apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: openpayd
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: openpayd
        tier: frontend
    spec:
      containers:
      - name: staticsite
        image: pureta/staticsite:firsttry
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
